python cross-platform build and test

diff --git a/bin/test b/bin/test
--- a/bin/test
+++ b/bin/test
@@ -1,49 +1,34 @@
-#!/usr/bin/perl
+#!/bin/bash
 
-use strict;
-use warnings;
+ok=0
+bad=0
 
-my $port = `./bin/port`; chomp $port;
-if ($? != 0) {
-    print "Could not find arduino serial port.\n";
-    exit(1);
-}
+for fin in "$@"
+do
+  fbase=${fin%%.in}
+  fout="$fbase.out"
 
-my $baud = `./bin/baud`; chomp $baud;
-if ($? != 0) {
-    print "Could not determine baud rate of test program.\n";
-    exit(1);
-}
+  echo "testing $fbase..."
 
-our $pass = 0;
-our $fail = 0;
+  ./bin/scraper.py < "$fin" > "$fout"
 
-foreach my $test (@ARGV)
-{
-  next if ($test =~ m/(\.out|\.test|-|~|#)$/);
-  next if ($test =~ m/^#|^\.#/);  
-  
-  open OLDOUT,     ">&STDOUT" or die "Can't dup STDOUT: $!";
-  open OLDERR,     ">&STDERR" or die "Can't dup STDERR: $!";
+  if diff -q "$fin" "$fout" >/dev/null 2>&1
+  then
+    echo "$fbase passed"
+    ok=$(($ok+1))
+  else
+    echo "$fbase failed"
+    diff -W 200 -y --left-column "$fin" "$fout"
+    bad=$(($bad+1))
+  fi
+done
 
-  open STDOUT, ">$test.test" or die "Can't redirect STDOUT: $!";
-  open STDERR, ">&STDOUT"     or die "Can't dup STDOUT: $!";
+count=$(($ok+$bad))
+echo "test meta summary: $ok passed, $bad failed, and 0 skipped, out of $count test(s)."
+if [ $bad -eq 0 ] ; then
+  exit 0
+else
+  exit 1
+fi
 
-  select STDERR; $| = 1;      # make unbuffered
-  select STDOUT; $| = 1;      # make unbuffered
 
-  system("./bin/tester",$port,$baud,$test);
-
-  open STDOUT, ">&", OLDOUT or die "Can't dup OLDOUT: $!";
-  open STDERR, ">&", OLDERR or die "Can't dup OLDERR: $!";
-
-  if ($? == 0) {
-      ++$pass;
-      print "$test ok\n";
-  } else {
-      ++$fail;
-      print "$test failed\n";
-  }
-}
-our $count = $pass + $fail;
-print "test meta-summary: $pass passed, $fail failed, and 0 skipped out of $count tests.\n";
