simpler includes cache_ide

diff --git a/ci/bin/arduino_exe b/ci/bin/arduino_exe
--- a/ci/bin/arduino_exe
+++ b/ci/bin/arduino_exe
@@ -1,26 +1,14 @@
 #!/bin/bash
 
-if [ "$(type -t os)" != "function" ]
-then
-    . "$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd)"/os
-fi
-
-if [ "$(type -t version)" != "function" ]
-then
-    . "$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd)"/version
-fi
-
-if [ "$(type -t dir_cache)" != "function" ]
-then
-    . "$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd)"/dir_cache
-fi
+for inc in os dir_cache version
+do
+    if [ "$(type -t $inc)" != "function" ]
+    then
+	. "$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd)"/$inc
+    fi
+done
 
 arduino_exe() {
-    if [ "$ARDUINO_EXE" != "" ]
-    then
-        echo "$ARDUINO_EXE"
-        return
-    fi
     OS="$(os "$@")"
     VERSION="$(version "$@")"    
     DIR_CACHE="$(dir_cache "$@")"
@@ -36,7 +24,22 @@ arduino_exe() {
     fi
 }
 
+arduino_exe_self_test() {
+    if ! arduino_exe | egrep -i -q "arduino\.[^.]*$"
+    then
+	echo "name test failed."
+	exit 1
+    fi
+    echo "arduino_exe ok"
+}
+
 if [[ "${BASH_SOURCE[0]}" == "${0}" ]]
 then
-    arduino_exe "$@"
+    if [ "$1" == "--self-test" ]
+    then
+        shift
+	arduino_exe_self_test "$@"
+    else
+	arduino_exe "$@"
+    fi
 fi
diff --git a/ci/bin/dir_cache b/ci/bin/dir_cache
--- a/ci/bin/dir_cache
+++ b/ci/bin/dir_cache
@@ -1,19 +1,12 @@
 #!/bin/bash
 
-if [ "$(type -t dir)" != "function" ]
-then
-    . "$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd)"/dir
-fi
-
-if [ "$(type -t os)" != "function" ]
-then
-    . "$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd)"/os
-fi
-
-if [ "$(type -t version)" != "function" ]
-then
-    . "$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd)"/version
-fi
+for inc in dir os version
+do
+    if [ "$(type -t $inc)" != "function" ]
+    then
+	. "$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd)"/$inc
+    fi
+done
 
 dir_cache() {
     OS="$(os "$@")"
@@ -23,7 +16,40 @@ dir_cache() {
     echo "${DIR}/cache/${VERSION}-${OS}"
 }
 
+dir_cache_self_test() {
+    if [ "$(dir_cache)" = "" ]
+    then
+	echo "default failed"
+        exit 1
+    fi
+
+    if [ "$(dir_cache --dir=a)" = "$(dir_cache --dir=b)" ]
+    then
+	echo "dir failed"
+        exit 1
+    fi
+
+    if [ "$(dir_cache --os=a)" = "$(dir_cache --os=b)" ]
+    then
+	echo "os failed"
+        exit 1
+    fi
+
+    if [ "$(dir_cache --version=a)" = "$(dir_cache --version=b)" ]
+    then
+	echo "version  failed"
+        exit 1
+    fi
+
+    echo "dir_cache_self_test: ok"
+}
+
 if [[ "${BASH_SOURCE[0]}" == "${0}" ]]
 then
-    dir_cache "$@"
+    if [ "$1" == "--self-test" ]
+    then
+	dir_cache_self_test "$@"
+    else
+	dir_cache "$@"
+    fi
 fi
