test ci

diff --git a/ci/bin/make_simavr_uno b/ci/bin/make_simavr_uno
--- a/ci/bin/make_simavr_uno
+++ b/ci/bin/make_simavr_uno
@@ -30,72 +30,93 @@ then
     . "$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd)"/avr_root
 fi
 
+if [ "$(type -t arduino_exe)" != "function" ]
+then
+    . "$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd)"/arduino_exe
+fi
+
+if [ "$(type -t cache_simavr)" != "function" ]
+then
+    . "$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd)"/cache_simavr
+fi
+
 make_simavr_uno() {
     DIR="$(dir "$@")"
     OS="$(os "$@")"
-    VERSIONS="$(versions "$@")"
+    VERSION="$(version "$@")"
+    ARDUINO_EXE="$(arduino_exe "$@")"
+    AVR_ROOT="$(avr_root "$@")"    
 
     while [ $# -gt 0 ]
     do
         case "$1"
         in
             --reload=*)    RELOAD=${1#--reload=}; shift;;
+            --branch=*)    BRANCH=${1#--branch=}; shift;;	    
             --*=*)         shift;;
             --)            shift; break;;
             *)             break;;
         esac
     done
 
-    if [ ! -d "$DIR/cache/simavr" -o "$RELOAD" = "true" ]
+    if [ $BRANCH = "" ]
     then
-	if ! cache_simavr --dir="$DIR" --reload="$RELOAD"
+	BRANCH=master
+    fi
+
+    if [ -x "$DIR/cache/${VERSION}-${OS}/simavr/uno" -a "$RELOAD" != "true" ]
+    then
+	exit 0
+    fi
+
+    if [ ! -r "$ARDUINO_EXE" ]
+    then
+	echo "Arduido executable $ARDUINO_EXE missing (caching)..."
+	if ! cache_ide "$@"
 	then
-	    echo "could not cache simavr"
 	    exit 1
 	fi
     fi
-    
-    for VERSION in $VERSIONS
-    do
-	if [ -x "$DIR/cache/${VERSION}-${OS}/simavr/uno" -a "$RELOAD" != "true" ]
-	then
-	   continue
-	fi
 
-	mkdir -p "$DIR/cache/$VERSION-$OS/simavr"
-	
-	AVR_ROOT="$(avr_root --dir="$DIR" --os="$OS" --version="$VERSION")"
-	if [ ! -d "$AVR_ROOT" ]
+    if [ ! -d "$AVR_ROOT" ]
+    then
+	echo "Missing avr tools directory $AVR_ROOT."
+	exit 1
+    fi
+
+    if [ ! -d "$DIR/cache/simavr" -o "$RELOAD" = "true" ]
+    then
+	echo "Missing simavr repository (caching)..."
+	if ! cache_simavr --dir=$DIR --reload=$RELOAD
 	then
-	    cache_ide --dir="$DIR" --os="$OS" --version="$VERSION" --reload="$RELOAD"
-	fi
-	if [ ! -d "$AVR_ROOT" ]
-	then
-	    echo "could not access avr_root='$AVR_ROOT'"
 	    exit 1
 	fi
+    fi
 
-	if [ ! -d "$DIR/cache/${VERSION}-${OS}/simavr" -o "$RELOAD" = "true" ]
-	then
-	    /bin/rm -rf "$DIR/cache/${VERSION}-${OS}/simavr"
-	    mkdir -p "$DIR/cache/${VERSION}-${OS}/simavr/repo"
-	    tar -C "$DIR/cache/simavr" -cf - . | tar -C "$DIR/cache/${VERSION}-${OS}/simavr/repo" -xf -
-	fi
+    /bin/rm -rf "$DIR/cache/${VERSION}-${OS}/simavr/repo"
+    mkdir -p "$DIR/cache/${VERSION}-${OS}/simavr/repo"
+    tar -C "$DIR/cache/simavr" -cf - . | tar -C "$DIR/cache/${VERSION}-${OS}/simavr/repo" -xf -
+    (cd "$DIR/cache/${VERSION}-${OS}/simavr/repo"; git checkout -f "$BRANCH")
 
-	mkdir -p "$DIR/cache/${VERSION}-${OS}/simavr"
-	if PATH="$AVR_ROOT/bin:$PATH" make -B -C "$DIR/cache/${VERSION}-${OS}/simavr/repo" clean build-simavr
-	then
-	    if PATH="$AVR_ROOT/bin:$PATH" make -B -C "$DIR/cache/${VERSION}-${OS}/simavr/repo/examples/board_simduino" clean all
-	    then
-		cp "$DIR/cache/${VERSION}-${OS}/simavr/repo/examples/board_simduino/"obj*/simduino.elf "$DIR/cache/${VERSION}-${OS}/simavr/uno"
-	    fi
-	fi
-	if [ ! -x "$DIR/cache/${VERSION}-${OS}/simavr/uno" ]
-	then
-	    echo "build failed."
-	    exit 1
-	fi
-    done
+    if ! PATH="$AVR_ROOT/bin:$PATH" make -B -C "$DIR/cache/${VERSION}-${OS}/simavr/repo" clean build-simavr
+    then
+	echo "build-simavr target failed."
+	exit 1
+    fi
+
+    if ! PATH="$AVR_ROOT/bin:$PATH" make -B -C "$DIR/cache/${VERSION}-${OS}/simavr/repo/examples/board_simduino" clean all
+    then
+       echo "build board_simduino target failed."
+       exit 1
+    fi
+
+    cp "$DIR/cache/${VERSION}-${OS}/simavr/repo/examples/board_simduino/"obj*/simduino.elf "$DIR/cache/${VERSION}-${OS}/simavr/uno"
+
+    if [ ! -x "$DIR/cache/${VERSION}-${OS}/simavr/uno" ]
+    then
+	echo "build failed."
+	exit 1
+    fi
 }
 	
 if [[ "${BASH_SOURCE[0]}" == "${0}" ]]
diff --git a/ci/bin/simavr_uno b/ci/bin/simavr_uno
--- a/ci/bin/simavr_uno
+++ b/ci/bin/simavr_uno
@@ -10,9 +10,9 @@ then
     . "$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd)"/os
 fi
 
-if [ "$(type -t versions)" != "function" ]
+if [ "$(type -t version)" != "function" ]
 then
-    . "$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd)"/versions
+    . "$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd)"/version
 fi
 
 simavr_uno_exit() {
@@ -29,13 +29,15 @@ simavr_uno_exit() {
 simavr_uno() {
     DIR="$(dir "$@")"
     OS="$(os "$@")"
-    VERSIONS="$(versions "$@")"
+    VERSION="$(version "$@")"
     HEX=""
 
     while [ $# -gt 0 ]
     do
         case "$1"
         in
+            --background=*)  BACKGROUND=${1#--background=}; shift;;
+	    --ino=*)    HEX="${1#--ino=}.hex"; shift;;
             --hex=*)    HEX="${1#--hex=}"; shift;;
             --*=*)      shift;;
             --)         shift; break;;
@@ -58,36 +60,26 @@ simavr_uno() {
     SIMAVR_UNO_PIDS=""
     trap simavr_uno_exit EXIT
 
-    for VERSION in $VERSIONS
+    PORT="/tmp/simavr-uart0"
+    "${DIR}/cache/${VERSION}-${OS}/simavr/uno" "${HEX}" &
+    PID=$!
+    if [ "$PID" != "" ]
+    then
+        SIMAVR_UNO_PIDS="$SIMAVR_UNO_PIDS $PID"
+    else
+        echo "could not launch simavr/uno"
+        exit 1
+    fi
+    
+    while [ ! -e "$PORT" ] ; do sleep 0.01 ; done
+    
+    cat "$PORT" 2>/dev/null | while read -r line
     do
-	PORT="/tmp/simavr-uart0"
-	"${DIR}/cache/${VERSION}-${OS}/simavr/uno" "${HEX}" &
-	PID=$!
-	if [ "$PID" != "" ]
+	echo "$line"
+	if [[ "$line" =~ "Test summary:" ]]
 	then
-            SIMAVR_UNO_PIDS="$SIMAVR_UNO_PIDS $PID"
-	else
-            echo "could not launch simavr/uno"
-            exit 1
+	    simavr_uno_exit
 	fi
-        
-	while [ ! -e "$PORT" ] ; do sleep 0.01 ; done
-	
-#	(for input in "${INPUT[@]}" ; do echo -n "$input\r\n" ; done) >> "$PORT" &
-#	PID=$!
-#	if [ "$PID" != "" ]
-#	then
-#            SIMAVR_UNO_PIDS="$SIMAVR_UNO_PIDS $PID"
-#	fi
-	
-	cat "$PORT" 2>/dev/null | while read -r line
-	do
-	    echo "$line"
-	    if [[ "$line" =~ "Test summary:" ]]
-	    then
-		simavr_uno_exit
-	    fi
-	done
     done
 }
 	
